version: '2'
services:
  koop-postgresql:
    image: postgres:12.3
    volumes:
      - ~/volumes/jhipster/koop/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=koop
      - POSTGRES_PASSWORD=asd
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5435:5432
