version: '2'
services:
  koop-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/koop/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=koop
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
