name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -Pprod -DskipTests=true package --file pom.xml

    - name: Docker Copy
      run: cp target/*.jar src/main/docker

    - name: Docker Build
      run: docker build -f src/main/docker/Dockerfile -t 164.68.100.154:5000/koop src/main/docker

    - name: Docker Push
      run: docker push 164.68.100.154:5000/koop


